server:
  port: 7777
#list:
#  user:
#    - asdf
#    - zxcv
#    - qwer
#name:
#  names:
#    - asdf
#    - zxcv
spring:
  profiles:
    active:
      - extra
#      - file
  #  application:
#    name: gateway-router
#  cloud:
#    gateway:
#      discovery:
#        locator:
#          enabled: true
  #      routes:
#        - id: server8002
#          #          uri: http://localhost:8001
#          uri: lb://server8002
#          predicates:
#            - Path=/client/**
#        - id: server800
#          #          uri: http://localhost:8001
#          uri: lb://server8002
#          predicates:
#            - Path=/api/**
  cloud:
    gateway: #存在nacos中
      default-filters:
        - DedupeResponseHeader=Vary Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST
      routes: #配置请求转发，
        - id: user-server
          uri: http://localhost:8001
          order: 1
          predicates:
            - Path=/api/user/**
        - id: sysuser-server
          uri: http://localhost:8002
          order: 2
          predicates:
            - Path=/api/sysUser/**
        - id: permission-server
          uri: http://localhost:8003
          order: 3
          predicates:
            - Path=/api/permission/**
        - id: role-server
          uri: http://localhost:8004
          order: 4
          predicates:
            - Path=/api/role/**
    sentinel:
      transport:
        dashboard: localhost:8080 #配置Sentinel dashboard地址

  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/rbac?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      username: root
      password: 123456
  redis:
    host: localhost
    port: 6379
    database: 3
    connect-timeout: 10000
    #自定义属性 过期时间
    expire: 60000
  jackson:
    date-format: yyyy-MM-dd
    time-zone: Asia/Shanghai
  mvc:
    format:
      date: yyyy-MM-dd
      date-time: yyyy-MM-dd HH:mm:ss
  main:
    web-application-type: reactive

